# Generated by Django 4.1.6 on 2023-03-21 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Project Title')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('start_date', models.DateField(verbose_name='Started at')),
                ('finish_date', models.DateField(blank=True, default=None, verbose_name='Ended at')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('In progress', 'In Progress'), ('New', 'New'), ('Done', 'Done')], default='New', max_length=100, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Task', 'Task'), ('Bag', 'Bug'), ('Enhancement', 'Enhancement')], default='Task', max_length=100, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('created_at', models.CharField(max_length=200, verbose_name='Created at')),
                ('ended_at', models.CharField(max_length=200, verbose_name='Ended at')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='task', to='webapp.project', verbose_name='Project')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='task', to='webapp.status', verbose_name='Status')),
                ('type', models.ManyToManyField(related_name='task', to='webapp.type', verbose_name='Type')),
            ],
        ),
    ]
