# Generated by Django 4.1.6 on 2023-03-16 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='task',
            name='ended_at',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Ended at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.CharField(max_length=200, verbose_name='Created at'),
        ),
    ]
