# Generated by Django 4.1.6 on 2023-03-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_task_updated_at_task_ended_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.ManyToManyField(related_name='types', to='webapp.type', verbose_name='Type'),
        ),
    ]
